site_name: Jonathan Monette | Personal Site
site_author: jmoney
site_description: ""
site_keyword: "jmoney, jonathan monette, engineer"
docs_dir: markdown

plugins:
  - search
  - macros
  - include-markdown

nav:
  - Home: index.md
  - Blogs: blogs/index.md
  - Cloud: cloud/index.md
  - Homebrew: homebrew/index.md 
  - TIL: 'https://jmoney.dev/til'
  - Resume: 'https://github.com/jmoney/resume/releases/download/latest/JonathanMonette_resume.pdf'

theme:
  name: github
  highlightjs: true
  hljs_style: github
  logo: img/favicon.ico